version: '3.8'

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  user_service:
    build:
      context: .
      dockerfile: cmd/user-service/Dockerfile
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME_USER}
      DB_SSLMODE: ${DB_SSLMODE}
    ports:
      - "${PORT_USER}:${PORT_USER}"
    depends_on:
      - postgres

  book_service:
    build:
      context: .
      dockerfile: cmd/book-service/Dockerfile
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME_BOOK}
      DB_SSLMODE: ${DB_SSLMODE}
    ports:
      - "${PORT_BOOK}:${PORT_BOOK}"
    depends_on:
      - postgres

volumes:
  pgdata:
